import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../lib/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio Federico Bellezza",
  description: "Generated by Federico Bellezza",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-linear-to-tr from-slate-700  to-gray-800 text-slate-800 overflow-x-hidden`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
